// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJBr-UiLZLwxqfQJnCeZx97EgVcjtc2lM',
    appId: '1:733436829123:web:c302312055d669e0e7f176',
    messagingSenderId: '733436829123',
    projectId: 'bike-rental-54725',
    authDomain: 'bike-rental-54725.firebaseapp.com',
    storageBucket: 'bike-rental-54725.appspot.com',
    measurementId: 'G-8NP9DFTQQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJBr-UiLZLwxqfQJnCeZx97EgVcjtc2lM',
    appId: '1:733436829123:android:c206ce7160678bf9e7f176',
    messagingSenderId: '733436829123',
    projectId: 'bike-rental-54725',
    storageBucket: 'bike-rental-54725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5gfuj4Twg84jmS0xgKkc7KdQR_c2CBfs',
    appId: '1:733436829123:ios:d5083419987c36ece7f176',
    messagingSenderId: '733436829123',
    projectId: 'bike-rental-54725',
    storageBucket: 'bike-rental-54725.appspot.com',
    iosBundleId: 'com.example.bikeRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5gfuj4Twg84jmS0xgKkc7KdQR_c2CBfs',
    appId: '1:733436829123:ios:636744caab0db060e7f176',
    messagingSenderId: '733436829123',
    projectId: 'bike-rental-54725',
    storageBucket: 'bike-rental-54725.appspot.com',
    iosBundleId: 'com.example.bikeRental.RunnerTests',
  );
}
